### ISSUE TITLE
fix:  melos does not work in combination with Dart workspace

### ISSUE THREAD

**Issue by DelcoigneYves** [invertase/melos#801] opened 2024-12-12 20:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

6.2.0

### Description

With release 3.27.0 of Flutter and the Dart 3.6.0 release, support was added for [Dart workspaces](https://dart.dev/tools/pub/workspaces). 

This speeds up the analyzer, and keeps all dependency resolutions in a single place (the root of the repo).

For our large projects, we are dividing our apps in subpackages, and manage the shared dependencies through melos, as well add some custom scripts to the melos.yaml file.

When adding a Dart workspace to our repository, `melos bootstrap` fails with the following error:

```
Cannot override workspace packages.
Package `app_health` at `../../../packages/core/app_health` is overridden in `../../../packages/providers/api/pubspec.yaml`.
Failed to update packages.
```

I believe this error is due to [this particular part](https://dart.dev/tools/pub/workspaces#dependency-overrides-in-a-workspace) in the workspaces documentation: we can only override a package once in a workspace. But, since melos creates a pubspec_overrides.yaml file for each subpackage, subpackages can be overridden multiple times.

Ideally, we could add a parameter to the melos.yaml file to configure where the pubspec_overrides should be created: for each package found, or only on the root level (or maybe even that is not needed, and we can just skip this step altogether).

### Steps to reproduce

1. Install and use Flutter 3.27.0
2. Create a new monorepo with some subpackages depending on each other. It's important at least two subpackages depend on the same third subpackage.
3. Configure a Dart workspace in the repo.
4. Add melos to the repo.
5. Run dart pub get
6. Run melos bootstrap

### Expected behavior

melos bootstrap should work together with Dart workspaces.

**Comment by spydon** [comment] 2024-12-12 20:28
Duplicate of #747

**Closed by spydon** 2024-12-12 20:28 UTC
Labels: bug

**Comment by spydon** [comment] 2024-12-12 20:29
If you don't have any specific things in your bootstrap step I think you could just skip it and the rest of the melos commands should work.

**Comment by DelcoigneYves** [comment] 2024-12-12 20:49
Looked over it, apologies for the confusion! Indeed when trying again now, it seems to work, must have been a caching issue.
