### ISSUE TITLE
Help me understand.!

### ISSUE THREAD

**Issue by richard457** [invertase/melos#190] opened 2021-11-01 08:13 UTC
I have packages
and I want to reference them in the main pubspec.yaml do I have to first publish them to https://pub.dev ? is there a way I can use them offline something like using the path

package:
   > path: 'path' 

I know this is something melos is solving, tried referencing the package after melos bootstrap, I was hoping I can reference my package directly like package: ^1.0.0 and melos can be clever enough to know that it should look the package from local dir, then not as it turn out that melos use also flutter pub get to update package which will always look the package from pub.dev,
so my question is, is there a way to fetch package from local something done by path?

**Comment by blaugold** [comment] 2021-12-05 14:46
This is a duplicate of #195.

**Closed** 2021-12-16 21:51 UTC
