### ISSUE TITLE
fix: melos publish fails when the packages are on a self hosted dart pub server

### ISSUE THREAD

**Issue by henriquezanfa** [invertase/melos#307] opened 2022-05-26 19:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.3.1

### Description

All my packages have set `publish_to: SELF HOSTED URL` on its pubspec.yaml, but when I try to run `melos publish` it shows:

```
Reading pub registry for package information... SUCCESS
Unhandled exception:
FormatException: Unexpected character (at character 1)
<!DOCTYPE html>
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:612:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      Package.getPublishedVersions (package:melos/src/package.dart:759:15)
<asynchronous suspension>
#7      _PublishMixin._getLatestPublishedVersionForPackages.<anonymous closure> (package:melos/src/commands/publish.dart:111:24)
<asynchronous suspension>
#8      Pool.forEach.run (package:pool/pool.dart:183:19)
<asynchronous suspension>
#9      Pool.withResource (package:pool/pool.dart:127:14)
<asynchronous suspension>
#10     Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
<asynchronous suspension>
```

I'm not sure if it's possible to publish to self hosted dart pub servers or if it is a bug. I'm using https://pub.dev/packages/unpub to server it.

### Steps to reproduce

1. Host a dart pub server with **unpub**
2. On a project that uses melos, add `publish_to: SELF HOSTED URL` to the pubspec.yaml
3. Run `melos publish --dry-run`

### Expected behavior

When running the `melos publish` command I would expect it to publish to the self hosted server. Instead, it crashes.

**Comment by blaugold** [comment] 2022-05-27 08:10
This seems like a bug in the `unpub` package. Melos makes a GET request to `<pub-server>/packages/<package-name>.json`, to which `unpub` seems to respond with a status code 200 and a HTML document. When Melos tries to parse this HTML document as JSON you get this error.

**Comment by henriquezanfa** [comment] 2022-05-31 00:49
I've cloned the upbub here and running a new project with the same configurations it is working fine. I need to try with the original repo again to understand what is going on.

**Comment by blaugold** [comment] 2022-07-18 20:31
As far as I can tell, the root of the issue is with `unpub`. I'm closing it for now. Please comment if there is more information pointing to a bug in Melos.

**Comment by mase7569** [comment] 2023-02-15 12:00
Crazy workaround **sketch**: 
find . -name 'pubspec_overrides.yaml' -exec rm {} \; && find packages -name 'pubspec.yaml' -depth 2 -execdir fvm flutter pub publish --force \; && melos bs

**Closed** 2023-03-08 20:51 UTC
Labels: bug, waiting for response
