### ISSUE TITLE
bootstrap hangs when package does not exist

### ISSUE THREAD

**Issue by Ehesp** [invertase/melos#195] opened 2021-11-16 10:52 UTC
If you add a dependency in a `pubspec.yaml` file which does not exist (both locally and on pub), the `melos bs` command will hang forever:

```
dependencies:
  fooooooo: ^0.0.1
  flutter:
    sdk: flutter
```

**Comment by richard457** [comment] 2021-12-17 09:36
Looking toward an update on this.

**Comment by blaugold** [comment] 2022-01-01 19:39
This looks like a duplicate of #135. Mabey best close one of them?

**Closed** 2022-01-02 12:46 UTC
Labels: bug, type: accepted
