### ISSUE TITLE
Dependency versioning

### ISSUE THREAD

**Issue by mark-apn** [invertase/melos#175] opened 2021-09-15 09:37 UTC
Hey all, Im wondering how dependency versioning works in melos. I cannot seem to find it in the documentation apart from a TODO. Would like to be able to declare dependencies (and dart/flutter environment constraints) that are then applied to all pubspecs.

![image](https://user-images.githubusercontent.com/62654433/133409548-8dfc2eb8-4202-45c5-b7ac-10fc56c960fd.png)

**Comment by blaugold** [comment] 2022-05-27 08:34
Closing this as a duplicate of #94.

**Closed by blaugold** 2022-05-27 08:34 UTC
