### ISSUE TITLE
fix:  dev_dependencies not working

### ISSUE THREAD

**Issue by gabulcw** [invertase/melos#791] opened 2024-11-08 12:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

6.2.0

### Description

I added a dev_dependencies to my `melos.yaml` to use intl_utils for all packages from my Project. So, when I run `melos bs`, the CLI doesn't add this package to any `pubspec.yaml`. The only way to do this is to add `dependencies`.

### Steps to reproduce

1 - add dev_dependencies:
2 - add intl_utils: 2.7.0
3 - run melos bs

### Expected behavior

When running __melos bs__ the expected behavior is to add all __pubpspec.yaml__ the package __intl_utils__ with dev_dependencies:

```yaml
dev_dependencies:
  intl_utils: 2.7.0

```

**Comment by spydon** [comment] 2024-11-08 12:17
Have you added it in the Bootstrap section?

**Comment by spydon** [comment] 2024-11-22 13:27
Closing this since we can't reproduce it and author is not replying with more info.

**Closed by spydon** 2024-11-22 13:27 UTC
Labels: bug, waiting for response
